### ISSUE TITLE
"NODE_ENV=development grommet pack" is not Windows-friendly

### ISSUE THREAD

**Issue by bmperrea** [grommet/grommet-cli#13]
As explained well [here](http://stackoverflow.com/questions/9249830/how-can-i-set-node-env-production-in-windows), one needs to call 
`"set NODE_ENV=production && grommet pack"`
on Windows. I would prefer an environment-independent solution here.

I'm still working out other issues so I will try to post a solution later.

**Comment by alansouzati** [comment]
Thanks so much for reporting this. We just had this problem this morning. I've released grommet-cli 2.1.4 with the fix for that and for opening the browser tab on windows as well. 

Please feel free to reopen it if you are still reproducing it in the latest grommet cli version.

**Comment by bmperrea** [comment]
Thanks so much to you! I hadn't gotten the PORT to work yet so this was really nice. Now the dev version is working.
