### ISSUE TITLE
test failed with vanilla app

### ISSUE THREAD

**Issue by bmperrea** [grommet/grommet-cli#14]
dev version worked. I'm using 2.1.4 with all of the defaults on Windows, just trying to follow [this video](https://vimeo.com/199912095). The server is running after calling `npm run dev-server` [again the dev version seems totally functional; I am having problems with the distribution version but that may be another story].

![test](https://cloud.githubusercontent.com/assets/5274371/22226602/f2f6643a-e17b-11e6-885e-e0c6a0b7ee79.PNG)

**Comment by alansouzati** [comment]
Interesting. this error makes totally sense and I'm not sure why I'm not able to reproduce it locally (I'm on a mac).

I will make sure to add these entries to the `.eslintrc` globals entry.

I believe this is how the .eslintrc should look like in the upcoming 2.1.5 version. I'm sorry about that.

```
{
  "extends": "airbnb",
  "env": {
    "node": true,
    "es6": true
  },
  "globals": {
    "it": true,
    "expect": true,
    "describe": true,
    "jest": true,
    "document": true,
    "test": true,
    "window": true,
    "fetch": true,
    "WebSocket": true,
    "alert": true
  },
  "rules": {
    "react/jsx-filename-extension": 0,
    "react/forbid-prop-types": 0,
    "react/jsx-boolean-value": 0,
    "react/jsx-first-prop-new-line": 0,
    "react/jsx-closing-bracket-location": 0,
    "react/no-multi-comp": 0,
    "import/no-unresolved": 0,
    "import/no-extraneous-dependencies": 0,
    "import/extensions": 0,
    "import/first": 0,
    "import/no-dynamic-require": 0,
    "jsx-quotes": ["error", "prefer-single"],
    "no-alert": 0,
    "no-use-before-define": 0,
    "no-console": 0,
    "no-tabs": 0,
    "no-param-reassign": 0,
    "no-underscore-dangle": 0,
    "comma-dangle": 0,
    "no-return-assign": 0,
    "no-plusplus": 0,
    "global-require": 0
  }
}
```

**Comment by bmperrea** [comment]
That worked. Thanks again! This is giving me a better idea of what depends on what. :)

I'll let you close this when 2.1.5 rolls out.

**Comment by alansouzati** [comment]
Done, https://github.com/grommet/grommet-cli/commit/638d7fe64dd4749aff8160392960278505d39b69

Thanks for reporting this!
