### ISSUE TITLE
Resources not being found in dist version

### ISSUE THREAD

**Issue by bmperrea** [grommet/grommet-cli#15]
- dev version worked. [I'm using 2.1.4 with all of the defaults on Windows.]
- test worked
- `grommet pack` works with no complaints, creating index.css and index.js
- `npm start` gives the following:

![start](https://cloud.githubusercontent.com/assets/5274371/22227256/43971a4e-e17f-11e6-8079-d9dd50059ceb.PNG)
![start2](https://cloud.githubusercontent.com/assets/5274371/22227258/452f0510-e17f-11e6-81ae-8a77ec89b6b1.PNG)

**Comment by alansouzati** [comment]
interesting. I have to be honest. I should have tested this with windows before releasing ahaha :)

Let me investigate how to solve that.

**Comment by alansouzati** [comment]
can you run ` npm install babel-cli --save` and try again?

Also can you validate that you have the following: `./node_modules/.bin/babel` ?

**Comment by alansouzati** [comment]
I believe this will fix the issue https://github.com/grommet/grommet-cli/commit/ff3f3611ea88c517e946e12fd11ab85be1abda06

I wait your feedback to close it.

**Comment by bmperrea** [comment]
I can confirm I did not have that file, and I'm guessing you're right. I will test it right now.

**Comment by bmperrea** [comment]
Yes, it `npm start` runs with now complaints now.

I am closing this but there's another issue coming about pathnames not being generated correctly in the distribution version. :)

**Comment by alansouzati** [comment]
I'm glad we have you submitting all these issues :)
