### ISSUE TITLE
Consider moving react-hmre to devServer config

### ISSUE THREAD

**Issue by karatechops** [grommet/grommet-cli#17]
I recently ran into an issue with the grommet cli app template when I added isomorphic rendering to my project. To resolve the `react-hmre` error I was receiving while starting the server I moved the `react-hmre` preset from the .babelrc config to the `devServer.config.babel.js` file. The config now looks like this:

```
import webpackConfig from './webpack.config.babel.js';

export default {
  compress: true,
  clientLogLevel: 'none',
  contentBase: webpackConfig.output.path,
  publicPath: webpackConfig.output.publicPath,
  quiet: true,
  hot: true,
  watchOptions: {
    ignored: /node_modules/
  },
  module: {
    loaders: [
      {
        test: /\.jsx?$/,
        exclude: /node_modules/,
        loader: 'babel',
        query: {
          presets: ['react-hmre']
        }
      }
    ]
  },
  historyApiFallback: true,
  proxy: {
    '/api/*': 'http://localhost:8102'
  }
};
```

This seemed to resolve the issue. I have not thoroughly tested this implementation but it should function similarly to the original implementation.

**Comment by alansouzati** [comment]
nice, can you craft a pull request for this? or you would prefer me to do it?

**Comment by karatechops** [comment]
I can PR but I'd like to test it out a bit more just to be sure this config works in all environments. I wanted to open up the conversation and see if there are any glaring reasons not to do this.

**Comment by alansouzati** [comment]
I fully support doing this. just make sure the hot reloading works in development

**Comment by karatechops** [comment]
This did end up breaking hot reloading. The issue I was facing is the server is trying to hot reload the isomorphically rendered react components because the node env is set to development. I ended up going back to the default config and changing the dev-server script to the following:

```
"dev-server": "NODE_ENV=devserver nodemon ./server/dev"
```

As long as the node environment on the dev server is not equal to 'development' I do not receive hot reload errors. I suppose this is project specific so no action will be needed in the template. When I get some downtime I will explore using the latest `react-hot-loader` in the webpack config instead of the babel preset.

**Comment by alansouzati** [comment]
nice. we used to have the react-hot-loader before, but the way it was implemented required an `AppContainer` inside the main `index.js` file. I was trying to avoid adding development code into the production bits. I found the babel preset to be less intrusive then the new beta `react-hot-loader`.

Thanks for looking into this.

**Comment by alansouzati** [comment]
I'm closing the issue for now, but feel free to reopen it if you believe there is something to be worked.
