### ISSUE TITLE
Static files are at the wrong path if you have a publicPath option set.

### ISSUE THREAD

**Issue by coltonw** [grommet/grommet-cli#18]
This is related to the following issue: https://github.com/webpack/webpack-dev-server/issues/288

Basically, if we have a public path, I would expect your `copyPublicFolder` to copy it to `dist/<publicPath>` rather than just to `dist`. At the very least I would want an option to add this behavior.

**Comment by alansouzati** [comment]
Interesting, I'm wanting to move the copy task to webpack itself using [copy-webpack-plugin](https://github.com/kevlened/copy-webpack-plugin).

This would expose the configuration and allow changes like that to happen.

Let me work on that now :)

**Comment by alansouzati** [comment]
Fixed in v2.2.0
