### ISSUE TITLE
Support Webpack v2

### ISSUE THREAD

**Issue by h-arlt** [grommet/grommet-cli#19]
Hi Folks,

Just saw the following notice on http://webpack.github.io/docs/:
> webpack v1 is deprecated. We encourage all developers to upgrade to webpack 2.

Since I'm using grommet-toolbox (don't know if this project is dead, so I'm reporting here instead) for building my Grommet app, it would be very cool to have support for Webpack v2.

Thx,
H

**Comment by alansouzati** [comment]
nice! let me work on webpack v2 support today! :)

**Comment by alansouzati** [comment]
Added support for it in 3.0.0 release

https://github.com/grommet/grommet-cli/releases/tag/v3.0.0

**Comment by h-arlt** [comment]
Wow, did not expect it to happen that rapidly ;) Many Thanks!
