### ISSUE TITLE
add support for `port` option inside webpack dev ser config

### ISSUE THREAD

**Issue by tafelito** [grommet/grommet-cli#25]
Changing the port number from the webpack.config.babel.js within the devConfig.devServer has no effect on the port number used. 

Right now the only way of changing the default port is to add the PORT env variable to the script

The webpack config file is created by default creating a new project using grommet

**Comment by alansouzati** [comment]
Fixed in https://github.com/grommet/grommet-cli/commit/15564f2d46635891bfe0f7f226ded06cb1d343eb

v3.0.1 released with support for that
