### ISSUE TITLE
transform-object-rest-spread missing in devDependencies present in .babelrc

### ISSUE THREAD

**Issue by dunnock** [grommet/grommet-cli#26]
Hi, just generated basic application with 
```
max$ grommet version
3.0.1
```

running `yarn dev` produces exception
```
max$ yarn dev
yarn dev v0.21.3
$ cross-env NODE_ENV=development grommet pack
[grommet:pack]: Running webpack...
/Users/max/src/comae/porosity-web/node_modules/babel-core/lib/transformation/file/options/option-manager.js:180
          throw new ReferenceError(messages.get("pluginUnknown", plugin, loc, i, dirname));
          ^

ReferenceError: Unknown plugin "transform-object-rest-spread" specified in "/Users/max/src/comae/porosity-web/.babelrc" at 0, attempted to resolve relative to "/Users/max/src/comae/porosity-web"
```

**Comment by alansouzati** [comment]
interesting. the basic template does not have the rest spread transform:

https://github.com/grommet/grommet-cli/blob/master/templates/basic/.babelrc

I'm assuming you executed `grommet new porosity-web --type basic` ?

**Comment by dunnock** [comment]
Sorry, that's my bad, I know what's happened, I generated with `--type app`, then removed `rm *` though it did not delete .babelrc, then regenreated `--type basic` .babelrc should have stayed.
