### ISSUE TITLE
grommet pack not generating dist/index.html

### ISSUE THREAD

**Issue by jocalafe** [grommet/grommet-cli#30]
I'm running 
`npm run dist `
and the html index file is not being generated, it does generate index.js and index.css.
![image](https://cloud.githubusercontent.com/assets/19539985/24920202/f8f8975a-1eab-11e7-88f2-0b6892b6e3a2.png)
also if I run
`npm  run dev`
the webpack sever doesnot serve the html file and it throws a 404 error
When I run
`npm run test` all linting and tests pass.
I'm running on windows.

**Comment by alansouzati** [comment]
do you have the CopyWebpackPlugin in your webpack config?

```
...
import CopyWebpackPlugin from 'copy-webpack-plugin';

let plugins = [
  new CopyWebpackPlugin([{ from: './public' }]),
  ...
];

....
```

I'm assuming you used an old version of the CLI. I remember in the past we used to copy this manually. Now we let the webpack config do it.

This feature has been introduced in the 2.2.0 version, check the release notes:

https://github.com/grommet/grommet-cli/releases/tag/v2.2.0

BTW, sorry for taking such a long time to get back to you on this.

**Comment by alansouzati** [comment]
I'm going to close this issue please feel free to reopen if you still think this is not working.
