### ISSUE TITLE
package.json depends on package outside of npm

### ISSUE THREAD

**Issue by steranka** [grommet/grommet-cli#36]
I'm working on build machine that doesn't allow access to github.com to ensure that all the code is in our local git repository, and npm repository.  When I tried to access this package using
`npm install -g grommet-cli`
I kept getting an error saying (and I'm paraphrasing)
```
Unable to download https://github.com/alansouzati/vorpal/tarball/EXIT_ON_PARSE
```
I tracked this down to the grommet-cli/package.json file containing a dependency for
vorpal which requires that file.

This is a request to publish the EXIT_ON_PARSE package to the normal npm repository so it will install normally without requesting a download from github.com.

Thank you,
Patrick

**Comment by alansouzati** [comment]
yeah I'm afraid I dont have a solution for this problem. We got a pull request open to add this feature to Vorpal (the tool behind our CLI) and the project seems to be "abandoned". 

Here is the PR:

https://github.com/dthree/vorpal/pull/169

We will re-evaluate the usage of vorpal in the future. But for now, unfortunately we need to use that branch.

**Comment by steranka** [comment]
I understand.  Thanks you for the consideration and quick response to the issue.
Please feel free to re-open it if it's appropriate.
