### ISSUE TITLE
tag and release v4.x on github

### ISSUE THREAD

**Issue by rasenplanscher** [grommet/grommet-cli#38]
Hey there,
I just updated my grommet project's dependencies and noticed the jump to `v4.0.1`. Since that might be a breaking change, I had a look at [the releases page](https://github.com/grommet/grommet-cli/releases) and was shocked to see the latest version listed being `v3.1.1`. I double-checked to make sure I had the correct package. Luckily, you mentioned v4 in your commit message for that, that made the verification less stressful :)

However, the update experience was still marred. Would you mind adding the tags and releases to prevent confusion with others?

Kind regards :D

**Comment by alansouzati** [comment]
fair. let me work on that right now.

**Comment by alansouzati** [comment]
https://github.com/grommet/grommet-cli/releases/tag/v4.0.0
