### ISSUE TITLE
Installs outdated grommet packages

### ISSUE THREAD

**Issue by NitroGhost** [grommet/grommet-cli#4]
I have just installed grommet-cli and used it to create a new grommet application started the dev server. Upon load I was disappointed to find that the whole page had a scrollbar on the right for no apparent reason, and quickly found out that there's a `overflow-y: scroll` on the html element so I went to the grommet page and found that this was an issue in 0.6.9. Checked package.json and low and behold, it's using 0.6.9 and not the latest version, even though grommet-cli was a new install.

Checking the package.json file shows that it has also installed an old grommet-toolbox, 0.2.0, instead of 0.3.7. I would assume that all dependencies in the package.json are outdated.

edit:

I have just checked to see how this works and it has annoyed me. I do not see the point in creating a grommet-cli if it cannot generate new and up to date grommet applications. It's massively pointless to have a cli that generates the apps from simply copying the files from a folder included **in the cli**. It makes much more sense to have the templates on github then download them to the users machine, and are kept updated with every iteration of grommet.

**Comment by alansouzati** [comment]
Thanks for reporting this issue. I'm going to fix this and make sure grommet-cli will always be using the latest possible Grommet bits.

**Comment by alansouzati** [comment]
hey @NitroGhost I wonder how you got 0.6.9 installed. If you look here:

https://github.com/grommet/grommet-cli/blob/master/templates/empty/package.json#L9

we add a caret `grommet: "^0.6.9"`, this makes the `npm install` grab anything in this range: `0.6.X`

You have a point regarding `grommet-toolbox`, I'm working right now updating it to 0.3.0. But in terms of Grommet core you should have the latest.

**Comment by alansouzati** [comment]
fixed in 1.0.0 release.

Event though grommet-cli is basically a copy from a template folder, we still believe it is a good idea to have it. I would say both solutions are good, and we like having the cli available that will be the starting point of grommet installation process.
