### ISSUE TITLE
proxy issue with dev mode

### ISSUE THREAD

**Issue by TulyOpt** [grommet/grommet-cli#44]
Hello, 

I create a new grommet app then I launch "npm run start" => it works.
I want to switch to dev environment : so I change the start script to "&& npm run **dev** &&", and relaunch "npm run start": 
The problem is that I can't login :  I have the error "Error occurred while trying to proxy request /api/sessions from localhost:8102 to http://localhost:8102"

I tried to update the devConfig by adding this line:
port : 8102,
but it doesn't work.

Can you help me ? Thanks,

**Comment by Ulisesgtz** [comment]
did you try to set the proxy? 
npm config set proxy http://{host}:{port}
npm config set https-proxy https://{host}:{port}

**Comment by TulyOpt** [comment]
Hello,

I solved this problem without modifying the scripts : 
I just launch two instances  : "npm run dev " and "npm run prod" and it works
