### ISSUE TITLE
Flash of odd shapes on startup of -full

### ISSUE THREAD

**Issue by tyrjo** [grommet/grommet-cli#5]
Using the -full template, I see a black triangle flash briefly on the screen between the grommet logo and the example application.

This makes it very painful to use the example application as a starting point because as I start to overwrite the sample application with my code I'm left with a very ugly startup screen.

**Comment by alansouzati** [comment]
looking into this. Just to clarify are you talking about the flash of unstyled content?

**Comment by alansouzati** [comment]
I don't have a fix for that yet. But I was able to reproduce it in Chrome and Firefox.

It seems related to sourceMaps for the css-loader. Grommet toolbox adds that in so that you can refer to the original SCSS styles when debugging your app. 

This is only happening during development mode.

**Comment by alansouzati** [comment]
In fact there is an open issue with css-loader on this already:

https://github.com/webpack/css-loader/issues/279

**Comment by alansouzati** [comment]
I'm closing this issue for now as I believe this is a problem with css-loader.
