### ISSUE TITLE
Countless errors related to grommet-icons

### ISSUE THREAD

**Issue by uyouthe** [grommet/grommet-cli#57]
I just created new Grommet app with grommet-cli. Now I'm doing `npm start` and I'm getting this:

```
ERROR in ./node_modules/grommet/es6/components/hocs.js
Module not found: Error: Can't resolve 'grommet-icons/es6/contexts/ThemeContext' in '/Users/*****/shtrafovnet/node_modules/grommet/es6/components'
 @ ./node_modules/grommet/es6/components/hocs.js 15:0-91 240:31-47
 @ ./node_modules/grommet/es6/components/AccordionPanel/AccordionPanel.js
 @ ./node_modules/grommet/es6/components/AccordionPanel/index.js
 @ ./node_modules/grommet/es6/components/index.js
 @ ./node_modules/grommet/es6/index.js
 @ ./src/App.js
 @ ./src/index.js
 @ multi (webpack)-dev-server/client?http://localhost:8080 ./src/index.js

ERROR in ./node_modules/grommet/es6/components/Box/Box.js
Module not found: Error: Can't resolve 'grommet-icons/es6/contexts/ThemeContext' in '/Users/*****/node_modules/grommet/es6/components/Box'
 @ ./node_modules/grommet/es6/components/Box/Box.js 13:0-91 147:38-54
 @ ./node_modules/grommet/es6/components/Box/index.js
 @ ./node_modules/grommet/es6/components/index.js
 @ ./node_modules/grommet/es6/index.js
 @ ./src/App.js
 @ ./src/index.js
 @ multi (webpack)-dev-server/client?http://localhost:8080 ./src/index.js
```

Countless of errors like these. I just can't get started, again! Page renders tho, but it has no icons, just blank rectangles that change their color on hover.

**Comment by uyouthe** [comment]
@alansouzati wow, really? That's amazing! I just can't get started with create-react-app with Grommet added. I tried adding it manually just [that way](https://github.com/grommet/grommet-starter-existing-app), but it appears to be unstyled somehow. 

Text is in Work Sans though, but everything else is unstyled.

Can you please help me with that? I'm starting a new shiny project and I want it to have the both latest create-react-app and Grommet. 

Or if you can't because of some reason, can I use grommet-react-app in production yet?

**Comment by alansouzati** [comment]
It seems that you are using Grommet v1 in a v2 platform. make sure your package.json is using `2.0.0-rc`, the latest official version is still v1. 

`grommet-react-app` is an ejected create-react-app for Grommet v1. I would not recommend starting with v1 at this point. 

`v2.0.0-rc` is a release candidate, and we are planning to officially release grommet v2 soon.

**Comment by textpain** [comment]
Okay, I’m not going to use cli anymore. How do I get styles to work in create-react-app v2 and Grommet v2?

**Comment by alansouzati** [comment]
it comes built in, you dont have to worry about it.

**Comment by textpain** [comment]
Yep! It seems like I messed it up somehow yesterday. Now I did all this from scratch and it works perfectly. 

Thanks a lot! The issue is solved.
