### ISSUE TITLE
Remove grommet splash from empty template

### ISSUE THREAD

**Issue by tyrjo** [grommet/grommet-cli#6]
When starting from the empty template I get an index page with the grommet ad. This is ~okay~ for the sample app templates I suppose (although I don't really like it)...but I'd like the empty application needs to start cleanly without requiring me to edit the index.html.

**Comment by alansouzati** [comment]
good idea, are you up for a pull request on that one?

**Comment by alansouzati** [comment]
Fixed in https://github.com/grommet/grommet-cli/commit/8e9b62659d7338dc9e34b43dbb296ee3286f117a
