### ISSUE TITLE
npm install by default is painful

### ISSUE THREAD

**Issue by tyrjo** [grommet/grommet-cli#7]
Trying to use grommet-cli to build a project that is going to run in a container. Just running grommet-cli to create a sample project ends up npm installing all the sample application dependencies on my local system. However, the next step is to copy the sample application source to a container, which will do its own npm install of the application dependencies.

I'd like grommet-cli to ONLY npm install its requirements needed to copy the template files into place...then let me run npm install of the app requirements separately.

**Comment by alansouzati** [comment]
fair request. I will add an option to skip install.

**Comment by alansouzati** [comment]
Fixed by https://github.com/grommet/grommet-cli/commit/74e5a5ffbeb4493265ed0b77aaa7452657c7ebef.

grommet-cli `1.1.0` released
