### ISSUE TITLE
Investigate grommet-cli + grommet-toolbox merger

### ISSUE THREAD

**Issue by alansouzati** [grommet/grommet-cli#9]
Start investigating the process of moving away from gulp as a task runner and use node to create the tasks we currently have in grommet-toolbox as part of that grommet-cli.

The idea is to install grommet globally and have the ability to run `grommet copy` instead of `gulp copy`. This is the same of all other tasks and pipelines.

**Comment by RyanCCollins** [comment]
@alansouzati would the idea be to keep using gulp behind the scenes, but make the same commands available through the grommet-cli interface, or would we be redoing the functionality of grommet-toolbox to get away from Gulp altogether?

**Comment by alansouzati** [comment]
The idea is to remove gulp altogether. I'm testing the installation and running time of `grommet check && grommet pack` and the improvement so far is impressive. About 35% faster installation time and 30% package time improvement.

**Comment by alansouzati** [comment]
The result of this investigation has been merged into grommet-cli, check it out:

https://github.com/grommet/grommet-cli/pull/10

**Comment by RyanCCollins** [comment]
Nice job on the merger!  The commands work great!

**Comment by alansouzati** [comment]
Thanks for the feedback @RyanCCollins
